#!/usr/bin/env bash
read -p "This prompt is unsupported. For text input use the pipe character (|) e.g \"echo \"This is a demo | rspaste\". Press Ctrl+C to exit\"" pipe
if [[ $pipe == "" ]]; then
  echo "Please enter something!"
  exit
else
  curl --data-binary @- https://paste.rs
fi
